### Get a chat room
GET http://localhost:5000/chat_rooms/1/6
Content-Type: application/json

### Get a chat room
GET http://localhost:5000/chat_rooms/getRoomById/4e6546fe-afec-4ec5-bf8e-ac238ff0a653

### Create a chat room
POST http://localhost:5000/chat_rooms/6/5
Content-Type: application/json