### Get a chat room
GET http://localhost:5000/chat_rooms/1/5
Content-Type: application/json

### Get a chat room
GET http://localhost:5000/chat_rooms/getRoomById/3ece20f6-49bc-4c35-a1a2-651c08a7df7c

### Create a chat room
POST http://localhost:5000/chat_rooms/1/5
Content-Type: application/json