### create new user
POST http://localhost:5000/authentications/login
Content-Type: application/json

{
      "email": "requinFR@gmail.com",
      "password": "password123"
}

###
GET http://localhost:5000/authentications/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjcxMzk1ODQ0fQ.GE8dUhORrCInbo1aG5JSD33Q3vqgmtaV4O60SnirkSc