### GET AZLL APPOINTMENTS FROM A USERE
GET http://localhost:5000/appointments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZXhwIjoxNjcxNDUzOTg5fQ.rG_jnAQEULtqJYVTitU0hf9HYyiDh-Ieup438zahLtM

### GET appointment where course id is 1 & user id is 1
GET http://localhost:5000/appointments/1/1

### POST a new appointment
POST http://localhost:5000/appointments/
Content-Type: application/json

{
  "id_course": 7,
  "id_student": 6,
  "appointment_date": "2022-10-20",
  "street" : "Avenue des champs ellysés",
  "number_house" : 12,
  "box_house" : "braaa"
}

### PUT update appointment where course id is 1 & user id is 1
PUT http://localhost:5000/appointments/1/1/state/pending
