### GET AZLL APPOINTMENTS FROM A USERE
GET http://localhost:5000/appointments/1

### GET appointment where course id is 1 & user id is 1
GET http://localhost:5000/appointments/1/1

### PUT update appointment where course id is 1 & user id is 1
PUT http://localhost:5000/appointments//1/state/pending
