### login user
POST http://localhost:5000/authentications/login
Content-Type: application/json

{
      "email": "requinFR@gmail.com",
      "password": "password123"
}


###
GET http://localhost:5000/authentications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZXhwIjoxNjcxNDkwMjQ0fQ.afWr7Gy7ARoO7Z9Wgr-tP2tSvv9M7pVGgxoJ3hJkK0k
