### Get a favorite
GET http://localhost:5000/favorites/1/2
Content-Type: application/json

### Get all your favorite teacher
GET http://localhost:5000/favorites/3
Content-Type: application/json

### Get the mosts favorites teachers
GET http://localhost:5000/favorites/mostFavoritesTeachers
Content-Type: application/json

### Add a favorite teacher
POST http://localhost:5000/favorites
Content-Type: application/json

{
  "id_student": 2,
  "id_teacher": 1
}

### Delete a favorite teacher
DELETE http://localhost:5000/favorites/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZXhwIjoxNjcxMzI0ODU5fQ.uKok27238qdQDsN7tfl-7viVzEqvkyoH4slHPW1h6kA

### ERROR ONLY ON DELETE 403 EVEN WITH TOKEN I CHECKED WITH STEFAN IF IT WORKS ELSWHERE